### PR TITLE
Use GPIO directory based on actual device tree path

### PR DESCRIPTION
**Pull request by VipSaran**
By testing the device tree directory we can detrermine whether to use the "old" `/sys/devices/virtual/gpio` path or to use the one used after update to kernel 3.18.x: `/sys/class/gpio`, so both configurations are supported.

### CODE REVIEW

**Comment by jfriend00** [comment]
This diff changes basic code formatting in ~50 places such that it is next to impossible to find what the functional change were to the code.  This would be a much better submission if the diff was only the functional changes.

**Comment by VipSaran** [comment]
Fixed with commit https://github.com/VipSaran/pi-gpio/commit/2636804fd4657665558a43a035055048141c85d2 (reverted the whitespace changes).

**Comment by jfriend00** [comment]
Finally found a way to see just the "net" diff: https://github.com/rakeshpai/pi-gpio/compare/master...VipSaran:master

**Comment by VipSaran** [comment]
@jfriend00 you "found the way" becuse I added another commit to the pull request, just as I commented above.

**Comment by jfriend00** [comment]
@VipSaran -  I know you added another commit.  But even then, neither one of your commits made it easy to see the "net" diff so I had to find a way to see a diff between two non-sequential versions on Github.  That's what I had to "find".  I'm not a github expert so you weren't making it easy to see the meaningful diff which is what I cared about - even with your additional commit.  When I found out how to do it, I thought I'd share so others could likewise just click on a link to see what functionally changed.

**Comment by VipSaran** [comment]
You don't have to be an expert. Just open Pull Request / Files Changed tab and you see the **absolute** difference between the upstream and the fork:
image

**Comment by lurch** [comment]
AFAIK you shouldn't ever need to use `/sys/devices/virtual/gpio` and you should always just use `/sys/class/gpio`, regardless of whether DeviceTree is being used or not?
As https://github.com/raspberrypi/linux/issues/791#issuecomment-73522636 explains.

**Comment by bestander** [comment]
:+1: can this be merged please?

**Comment by jsavko** [comment]
This patch also makes it work with the Raspberry Pi 2 B.  I was testing it last night.

**Comment by rakeshpai** [comment]
Published to npm as 0.0.7. Thanks, @VipSaran @jfriend00 @jsavko.

**Comment by VipSaran** [comment]
Thanks @rakeshpai

**Pull request merged**
