### PR TITLE
Promises Refactor

### PR DESCRIPTION
**Pull request by leefernandes**
I found that my project using pi-gpio cleaned up quite well with promises.  Here's a promise based flavor if interested.  

I think this could go even further, and benefit by a "Pin" object for usage like:

```
// gpio.open could create a "Pin" object (if a pinNumber is passed) and resolve
// with other gpio methods expecting a "Pin" object
gpio.open(16)
  .then(gpio.read)
  .then(function(pin) {
    console.log('pin value', pin.value);
    gpio.close(pin)
  })
```

Thanks!

### CODE REVIEW

**Comment by jopnick** [comment]
I have to agree with leaving as callbacks. It at least gives the option for those who are familiar with this pattern.  There is already a pi-gpio-promise, for those wanting to use promise patterns. It's also as simple as gpio.write = Promise.promisify(gpio.write) for those who want it all

**Comment by arthurlm** [comment]
If you merge this refactoring using promises instead of callbacks, maybe you should first tag the current code as a first release (v1.0).

This will help current developers to do not break the compatibility of their code.

**Comment by kbowerma** [comment]
yay

**Comment by Billy-** [comment]
Return a promise **_and_** accept a callback!! :smiley:

**Comment by cagodoy** [comment]
+1 for promises

**Comment by socar-chef** [comment]
Return promise and accept callback is best i think. Like google-cloud library. And it allows third party promise like bluebird.

**Pull request closed without merging**
